
// anonymous function
// this function deals with the requests for quizzes
module.exports = (app) => {

    let quizzes = [
        {_id: "123", title: "quiz 1"},
        {_id: "234", title: "quiz 2"},
        {_id: "345", title: "quiz 3"}
    ]

    const findAllQuizzes = (req, res) => {
        res.send(quizzes)
    }

    const findQuizById = (req, res) => {
        // param is a map generated by request and parses out path var
        const quizId = req.params["qid"]
        const quiz = quizzes.find(quiz => quiz._id === quizId)
        res.send(quiz)
    }

    const createQuiz = (req, res) => {
        const quiz = {
            _id: new Date().getTime() + "",
            title: "New Quiz"
        }
        quizzes.push(quiz)
        res.send(quiz)
    }

    const deleteQuiz = (req, res) => {
        const quizId = req.params.qid
        quizzes = quizzes.filter(quiz => quiz._id !== quizId)
        // res.send(quizzes)
        res.send(200)
    }


    const updateQuiz = (req, res) => {
        // everything sent from client is in request object
        const quizId = req.params.qid
        const newQuiz = req.body
        // use map to rebuild the array
        quizzes = quizzes.map(quiz => quiz._id === quizId ? newQuiz : quiz)
        res.send(200)
    }



    app.get("/quizzes", findAllQuizzes)
    app.get("/quizzes/:qid", findQuizById)
    app.post("/quizzes", createQuiz)
    app.delete("/quizzes/:qid", deleteQuiz)
    app.put("/quizzes/:qid", updateQuiz)


}


// Node.js export mechanism
// whoever assigned to exports becomes available to require function
// module.exports = service
